### ISSUE TITLE
Will not install on VS2022 arm64

### ISSUE THREAD

**Issue by garkpit** [madskristensen/AddAnyFile#146]
**Describe the bug**
Error when trying to install.

**To Reproduce**
Using latest Win 11 arm64 (on Parallels on Mac / Apple Silicon)
And latest VS2022
Downloaded from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.AddNewFile64
Double clicked the vsix

**Expected behavior**
It should install

**Screenshots**
(log below)

**Additional context**
I have just moved from PC to Mac (from hovercraft to utter silence). Naturally worried I would have trouble with all my dev tools etc. But Parallels + Windows 11 arm64 has been mostly trouble free. Very happy! This morning realised I had not installed all my favourite extensions and yours was the first I tried to find. It does not appear in the Manage Extensions list in VS, but found it on the Marketplace web site..
Just realised arm64 and amd64 look very similar but are of course completely different things.. So perhaps this is not a bug but a feature/capability request :)
 
Here is the log:
17/08/2023 07:06:07 - Microsoft VSIX Installer
17/08/2023 07:06:07 - -------------------------------------------
17/08/2023 07:06:07 - vsixinstaller.exe version:
17/08/2023 07:06:07 - 17.7.2189+bd7ee5fd3b
17/08/2023 07:06:07 - -------------------------------------------
17/08/2023 07:06:07 - Command line parameters:
17/08/2023 07:06:07 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\AddAnyFile.vsix
17/08/2023 07:06:07 - -------------------------------------------
17/08/2023 07:06:07 - Microsoft VSIX Installer
17/08/2023 07:06:07 - -------------------------------------------
17/08/2023 07:06:09 - Initializing Install...
17/08/2023 07:06:09 - Searching for applicable products...
17/08/2023 07:06:10 - Found installed product - Visual Studio Community 2022
17/08/2023 07:06:10 - Found installed product - Global Location
17/08/2023 07:06:10 - Extension Details...
17/08/2023 07:06:10 - 	Identifier         : d48e8f25-661b-4970-8b66-03f051ba5fc3
17/08/2023 07:06:10 - 	Name               : Add New File (64-bit)
17/08/2023 07:06:10 - 	Author             : Mads Kristensen
17/08/2023 07:06:10 - 	Version            : 4.1.8
17/08/2023 07:06:10 - 	Description        : The fastest and easiest way to add new files to any project - including files that start with a dot
17/08/2023 07:06:10 - 	Locale             : en-US
17/08/2023 07:06:10 - 	MoreInfoURL        : https://github.com/madskristensen/AddAnyFile
17/08/2023 07:06:10 - 	InstalledByMSI     : False
17/08/2023 07:06:10 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
17/08/2023 07:06:10 - 	SignatureState     : Unsigned
17/08/2023 07:06:10 - 	Supported Products : 
17/08/2023 07:06:10 - 		Microsoft.VisualStudio.Pro
17/08/2023 07:06:10 - 			Version : [17.0,18.0)
17/08/2023 07:06:10 - 			ProductArchitecture : amd64
17/08/2023 07:06:10 - 	References         : 
17/08/2023 07:06:10 - 	Prerequisites      : 
17/08/2023 07:06:10 - 		-------------------------------------------------------
17/08/2023 07:06:10 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
17/08/2023 07:06:10 - 		Name         : Visual Studio core editor
17/08/2023 07:06:10 - 		Version      : [15.0,)
17/08/2023 07:06:10 - Signature Details...
17/08/2023 07:06:10 - 	Extension is not signed.
17/08/2023 07:06:10 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 186
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 28
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 101
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 42
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 267
   at VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 225
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

PS: Love your work! Many thanks for the add-ons :)  Is it odd that this is the one I use the most? :D

**Comment by garkpit** [comment]
So, I downloaded the source and had a go myself. It won't work because it uses libraries that are not Arm64 compatible. I asked GPT4 and it said:

![image](https://github.com/madskristensen/AddAnyFile/assets/1252126/df0c8f5e-cde3-4fd6-9c2b-fa5d8603da02)

Not a quick fix for you either I guess! Oh well, I'll have to learn a new keyboard shortcut, or something... :)

**Comment by garkpit** [comment]
Not a 'Bug' but an Enhancement / Request
Can't figure out how to change the label, sorry
