### ISSUE TITLE
Doesn't work with Visual F# Power Tools

### ISSUE THREAD

**Issue by Lenne231** [madskristensen/AddAnyFile#38]
### Installed product versions
- Visual Studio: [2015 Community]
- This extension: [3.5.113]

### Description
Visual F# Power Tools extension allows me to add folders to F# projects, but when i try to add a new file to a folder using this extension, the file is in the folder on the file system but not in the folder in the project system.

**Comment by Lenne231** [comment]
```
01.10.2016 09:09:23: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.FSharp.ProjectSystem.MSBuildUtilities.MoveFileToBottomOfGroup(String relativeFileName, ProjectNode projectNode)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.MoveFileToBottomIfNoOtherPendingMove(String relativeFileName)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.DoAddItem(UInt32 itemIdLoc, VSADDITEMOPERATION op, String itemName, UInt32 filesToOpen, String[] files, IntPtr dlgOwner, VSADDRESULT[] result, AddItemContext addItemContext)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAProjectItems.<>c__DisplayClass4.<AddItem>b__5()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAProjectItems.AddItem(String path, VSADDITEMOPERATION op)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAProjectItems.AddFromFile(String fileName)
   at MadsKristensen.AddAnyFile.ProjectHelpers.AddFileToProject(Project project, FileInfo file, String itemType) in C:\projects\addanyfile\src\Helpers\ProjectHelpers.cs:line 108
   at MadsKristensen.AddAnyFile.AddAnyFilePackage.<MenuItemCallback>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:line 83
```
