### ISSUE TITLE
Lots of exceptions and E_FAIL messages in Output Window (successfully executes though)

### ISSUE THREAD

**Issue by astrohart** [madskristensen/AddAnyFile#84]
### Installed product versions
- Visual Studio: 2019 Enterprise v16.9.2
- This extension: 3.5.150

### Description
When I add a new file, the Output window fills with the following messages:

```
3/21/2021 2:35:54 PM: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at MadsKristensen.AddAnyFile.AddAnyFilePackage.<ExecuteAsync>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:line 152
3/21/2021 2:36:23 PM: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at MadsKristensen.AddAnyFile.AddAnyFilePackage.<ExecuteAsync>d__2.MoveNext() in C:\projects\addanyfile\src\AddAnyFilePackage.cs:line 152
```

Screenshot:
![image](https://user-images.githubusercontent.com/8261875/111916836-40434080-8a53-11eb-98e9-300c7f86cc4b.png)
**Figure 1.** Output window showing error messages.

Despite the errors being shown, the extension appears to work as expected otherwise.  While I am not 100% sure these messages have not been displayed using prior VS 2019 versions, I only started noticing this by updating the IDE to v16.9.2.

This is a minor severity issue; the extension meets my needs otherwise.

### Steps to recreate
1. Install the extension into VS 2019 Enterprise v16.9.2.
2. Create a new project of any type.
3. Press `SHIFT+F2` to activate the **Add New File** dialog box.
4. Add a new file with a `.cs` extension (I have not tried it for others)
5. Works as expected; however, the Output window appears and is filled with error messages as shown above.

### Current behavior
The output window fills with error messages, but the product seems to work as designed.

### Expected behavior
No error messages in the Output window.

**Comment by reduckted** [comment]
This should have been fixed by #82. 😄

**Comment by No0Vad** [comment]
Any idea when the extension will be updated too? [Marketplace link](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.AddNewFile)
